name: advancedpianistrobot
version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: pianist-backend
    ports:
      - "9000:8080"          # host:container  (host = 8000, container = 8080)
    env_file:
      - ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]  # volitelně
      interval: 30s
      timeout: 5s
      retries: 5

  expo-frontend:
    build:
      context: ./frontend
    container_name: pianist-frontend
    ports:
      - "5112:80"            # nginx poslouchá na 80
    env_file:
      - ./backend/.env       # pokud tu máš VITE_API_URL apod.
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
